### USER
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "name": "muhammad al imran 10",
  "email": "muhammadalimran10@gmail.com",
  "password": "imran12345",
  "profile": {
    "identifyType": "KTP",
    "identifyNumber": "1234567890",
    "address": "Aceh 10"
  }
}


###
GET http://localhost:3000/api/v1/users

###
GET http://localhost:3000/api/v1/users/1

###
GET http://localhost:3000/api/v1/pagination-user?limit=5&page=1

###
DELETE http://localhost:3000/api/v1/users/10


###
PUT http://localhost:3000/api/v1/users/1
Content-Type: application/json

{
  "name": "muhammad al imran 1",
  "email": "muhammadalimran1@gmail.com",
  "password": "imran12345",
  "profile": {
    "identifyType": "KTP",
    "identifyNumber": "1234567890",
    "address": "Aceh 1"
  }
}

### ACCOUNT
POST http://localhost:3000/api/v1/accounts
Content-Type: application/json

{
  "userId": 10,
  "bankName": "Bank BNI",
  "bankAccountNumber": "1234567890",
  "balance": 5000.00
}

###
GET http://localhost:3000/api/v1/accounts

###
GET http://localhost:3000/api/v1/accounts/1

###
DELETE http://localhost:3000/api/v1/accounts/9

###
PUT http://localhost:3000/api/v1/accounts/9
Content-Type: application/json

{
  "bankName": "Bank Aceh",
  "bankAccountNumber": "1234567890",
  "balance": 500000.00
}


### TRANSAKSI
POST http://localhost:3000/api/v1/transactions
Content-Type: application/json

{
  "sourceAccountId": 1,
  "destinasiAccountId": 2,
  "amount": 200
}

###
GET http://localhost:3000/api/v1/transactions

###
GET http://localhost:3000/api/v1/transactions/1
