### USER
POST http://localhost:8000/api/v1/users
Content-Type: application/json

{
  "name": "muhammad al imran 10",
  "email": "muhammadalimran10@gmail.com",
  "password": "imran12345",
  "profile": {
    "identifyType": "KTP",
    "identifyNumber": "1234567890",
    "address": "Aceh 10"
  }
}


###
GET http://localhost:8000/api/v1/users


###
GET http://localhost:8000/api/v1/users/12
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsImlhdCI6MTY5NzcwMzkzOX0.WKyBZhJOgPvqHkbmG25pGOrJhdZcujfS3WdWX6yoyNY

###
GET http://localhost:8000/api/v1/pagination-user?limit=5&page=1

###
DELETE http://localhost:8000/api/v1/users/5


###
PUT http://localhost:8000/api/v1/users/11
Content-Type: application/json

{
  "name": "muhammad al imran 1",
  "email": "muhammadalimran1@gmail.com",
  "password": "imran12345",
  "profile": {
    "identifyType": "KTP",
    "identifyNumber": "1234567890",
    "address": "Aceh 1"
  }
}

### ACCOUNT
POST http://localhost:8000/api/v1/accounts
Content-Type: application/json

{
  "userId": 11,
  "bankName": "Bank BNI",
  "bankAccountNumber": "1234567890",
  "balance": 5000.00
}

Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsImlhdCI6MTY5NzcwMzkzOX0.WKyBZhJOgPvqHkbmG25pGOrJhdZcujfS3WdWX6yoyNY

###
GET http://localhost:8000/api/v1/accounts

###
GET http://localhost:8000/api/v1/accounts/1

###
DELETE http://localhost:8000/api/v1/accounts/16

###
PUT http://localhost:8000/api/v1/accounts/1
Content-Type: application/json

{
  "bankName": "Bank Aceh",
  "bankAccountNumber": "1234567890",
  "balance": 500000.00
}


### TRANSAKSI
POST http://localhost:8000/api/v1/transactions
Content-Type: application/json

{
  "sourceAccountId": 7,
  "destinasiAccountId": 8,
  "amount": 1000
}

Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsImlhdCI6MTY5NzcwMzkzOX0.WKyBZhJOgPvqHkbmG25pGOrJhdZcujfS3WdWX6yoyNY

###
GET http://localhost:8000/api/v1/transactions

###
GET http://localhost:8000/api/v1/transactions/3


###
POST http://localhost:8000/api/v1/auth/register
Content-Type: application/json

{
    "name":"imran22",
    "email":"imran22@mail.com",
    "password":"imran12345",
    "password_confirmation":"imran12345",
    "profile": {
      "identifyType": "KTP",
      "identifyNumber": "1234567890",
      "address": "Aceh 1"
  }
}


###
POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
    "email":"imran22@mail.com",
    "password":"imran12345"
}

###
GET http://localhost:8000/api/v1/auth/whoami
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsImlhdCI6MTY5NzcwMzkzOX0.WKyBZhJOgPvqHkbmG25pGOrJhdZcujfS3WdWX6yoyNY